# Generated by Django 6.0.2 on 2026-02-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="name",
        ),
    ]
